name: Train and Evaluate Model

on:
  workflow_dispatch:
    inputs:
      epochs:
        description: "Number of training epochs"
        required: true
        default: "50"
      lr:
        description: "Learning rate"
        required: true
        default: "0.01"

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pipx and uv
        run: |
          python -m pip install --upgrade pip
          pip install pipx
          pipx install uv

      - name: Install dependencies via uv
        run: |
          uv pip install --system --strict --group default

      - name: Run training
        run: |
          python PyTorchLoader_mlflow.py --epochs ${{ inputs.epochs }} --lr ${{ inputs.lr }}

  evaluate:
    runs-on: ubuntu-latest
    needs: train

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pipx and uv
        run: |
          python -m pip install --upgrade pip
          pip install pipx
          pipx install uv

      - name: Install dependencies via uv
        run: |
          uv pip install --system --strict --group default

      - name: Run evaluation
        run: |
          python PyTorchPerdiction.py
