name: Train and Evaluate Model

on:
  workflow_dispatch:
    inputs:
      epochs:
        description: "Number of training epochs"
        required: true
        default: "10"
      learning_rate:
        description: "Learning rate"
        required: true
        default: "0.01"

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install uv and create virtualenv
        run: |
          pip install uv
          uv venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          uv pip install --all

      - name: Run training
        run: |
          .venv/bin/python PyTorchLoader_MLflow.py --epochs ${{ github.event.inputs.epochs }} --lr ${{ github.event.inputs.learning_rate }}

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: regression_model.pt

  evaluate:
    runs-on: ubuntu-latest
    needs: train

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download model artifact
        uses: actions/download-artifact@v4
        with:
          name: model
          path: .

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install uv and create virtualenv
        run: |
          pip install uv
          uv venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          uv pip install --all

      - name: Run evaluation
        run: .venv/bin/python PyTorchPerdiction.py
